import "server-only";

import {
  CopilotRuntime,
  CopilotKitIntelligence,
  InMemoryAgentRunner,
} from "@copilotkit/runtime/v2";
import { HttpAgent } from "@ag-ui/client";

/**
 * The Intelligence runtime from the Intelligence Quickstart, built once and
 * mounted twice.
 *
 * The doc builds a runtime in "Connect your runtime" and then exposes it in
 * "Expose one Runtime route". Those two steps used to prescribe the multi-route
 * handler; as of the 2026-09-09 sync the second one prescribes
 * `mode: "single-route"` instead, and the frontend step gained
 * `useSingleEndpoint`. Both mounts are kept so the difference under test is the
 * transport and nothing else:
 *
 *   `/api/copilotkit-threads` — multi-route, drives the three Rich Threads
 *                               routes. Still what `threads`,
 *                               `threads-lifecycle`, `headless-threads` and the
 *                               drawer page publish.
 *   `/api/copilotkit-single`  — single-route, drives `/intelligence/quickstart`.
 *                               What this page now publishes.
 *
 * A factory rather than a shared instance: each route builds its own so neither
 * mount can be affected by the other's channel activation.
 *
 * The three credentials below come from `frontend/.env.local`, copied from the
 * project `copilotkit init` scaffolded under `1cli-testing/`. Nothing here logs
 * in: `COPILOTKIT_LICENSE_TOKEN` is an EdDSA-signed JWT that
 * `@copilotkit/license-verifier` checks offline against a bundled public key.
 * `CPK_INTELLIGENCE_API_KEY` is the project key for the managed thread store, so
 * threads written here land in the same project as the CLI app.
 */

const AGENT_URL = process.env.MS_AGENT_URL ?? "http://localhost:8000";

// Treat empty/whitespace values as absent. A GitHub Actions `${{ secrets.X }}`
// reference to a secret that does not exist expands to an empty string, which
// still *defines* the variable — so a plain `??` or truthiness check on
// process.env would sail past it and hand Intelligence an empty credential.
const firstSet = (...values: (string | undefined)[]) =>
  values.find((v) => typeof v === "string" && v.trim().length > 0)?.trim();

// `CPK_INTELLIGENCE_API_KEY` is the name the docs now publish, so it is read
// first. `INTELLIGENCE_API_KEY` is what older CLIs wrote and stays accepted —
// the docs renamed the variable without saying the old one stopped working.
const INTELLIGENCE_KEY = firstSet(
  process.env.CPK_INTELLIGENCE_API_KEY,
  process.env.INTELLIGENCE_API_KEY,
);
const LICENSE_TOKEN = firstSet(process.env.COPILOTKIT_LICENSE_TOKEN);

/** True when both credentials are present, so Intelligence is actually wired. */
export const INTELLIGENCE_CONFIGURED = Boolean(
  INTELLIGENCE_KEY && LICENSE_TOKEN,
);

const mainAgent = () => new HttpAgent({ url: `${AGENT_URL}/` });

export function createIntelligenceRuntime(): CopilotRuntime {
  return new CopilotRuntime({
    // `default` is registered because `<CopilotThreadsDrawer>` and `useThreads`
    // fall back to DEFAULT_AGENT_ID ("default") when no agentId is given, and
    // threads are stored per agent id. `my_agent` mirrors the main runtime so
    // the same prompts work on both.
    agents: {
      default: mainAgent(),
      my_agent: mainAgent(),
      sample_agent: new HttpAgent({ url: `${AGENT_URL}/sample_agent` }),
      search_agent: new HttpAgent({ url: `${AGENT_URL}/search_agent` }),
    },

    // Without a license token the runtime still answers the read-only thread
    // routes off the in-memory runner's local-dev fallback (list, messages,
    // events, state). Rename/archive/delete and realtime sync return 422, and
    // `/info` omits `licenseStatus`, which leaves the prebuilt drawer locked.
    ...(INTELLIGENCE_KEY && LICENSE_TOKEN
      ? {
          intelligence: new CopilotKitIntelligence({
            apiKey: INTELLIGENCE_KEY,
            ...(process.env.INTELLIGENCE_API_URL
              ? { apiUrl: process.env.INTELLIGENCE_API_URL }
              : {}),
            ...(process.env.INTELLIGENCE_GATEWAY_WS_URL
              ? { wsUrl: process.env.INTELLIGENCE_GATEWAY_WS_URL }
              : {}),
          }),
          // Thread names are auto-generated by the LLM after the first message.
          // Spelled out rather than left to the default so the flag is visible
          // next to the docs' `generateThreadNames: false`.
          // [1] headless-threads: runtime options
          // [!code highlight]
          generateThreadNames: true,

          // Lock options from the same doc step, left at their defaults:
          // lockTtlSeconds: 20,               // max 3600
          // lockHeartbeatIntervalSeconds: 15, // max 3000
          // lockKeyPrefix: "cpk-ms-agent",    // when apps share one Redis

          // Threads are stored per user, so the runtime has to name one. The
          // doc calls a static value demo-only, and that is exactly what this
          // is: a fixed id keeps one shared list across browsers for manual QA.
          // Send `x-copilotkit-user-id` to check that two users get two
          // separate lists.
          // [2] threads-lifecycle: scope threads to the signed-in user
          // [3] intelligence quickstart: identifyUser
          // [!code highlight]
          identifyUser: (request: Request) => {
            const id =
              request.headers.get("x-copilotkit-user-id") ?? "demo-user";
            return { id, name: id === "demo-user" ? "Demo User" : id };
          },
          licenseToken: LICENSE_TOKEN,
        }
      : { runner: new InMemoryAgentRunner() }),
  });
}
